export enum SOCIAL_TYPE {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  KAKAO = 'KAKAO',
  NAVER = 'NAVER',
}

export enum GLOBAL_ROLE {
  ROLE_USER = 'ROLE_USER',
  ROLE_ADMIN = 'ROLE_ADMIN',
}

export enum FREEMIUM_TIER {
  BETA = 'BETA',
  STARTER = 'STARTER',
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}

export enum APPROVAL_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ALLOWED_STATUS {
  AGREE = 'AGREE',
  DISAGREE = 'DISAGREE',
}
