export enum SOCIAL_TYPE {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  KAKAO = 'KAKAO',
  NAVER = 'NAVER',
}

export enum GLOBAL_ROLE {
  ROLE_USER = 'ROLE_USER',
  ROLE_ADMIN = 'ROLE_ADMIN',
}

export enum FREEMIUM_TIER {
  BETA = 'BETA',
  STARTER = 'STARTER',
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}

export enum APPROVAL_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ALLOWED_STATUS {
  AGREE = 'AGREE',
  DISAGREE = 'DISAGREE',
}

export enum CHALLENGE_CATEGORY {
  STUDYING = 'STUDYING',
  EXERCISE = 'EXERCISE',
  READING = 'READING',
  NEWSPAPER = 'NEWSPAPER',
  COPYING = 'COPYING',
  DIARY_WRITING = 'DIARY_WRITING',
  LIFESTYLE_HABITS = 'LIFESTYLE_HABITS',
  ETC = 'ETC',
}

export enum CHALLENGE_LOG_TYPE {
  GENERAL = 'GENERAL',
  RECORDING = 'RECORDING',
}

export enum S3_FOLDER {
  ACADEMY_IMAGE = 'ACADEMY_IMAGE',
  PROFILE_IMAGE = 'PROFILE_IMAGE',
  CHALLENGE_CORE_THUMBNAIL_IMAGE = 'CHALLENGE_CORE_THUMBNAIL_IMAGE',
  CHALLENGE_CORE_FILE = 'CHALLENGE_CORE_FILE',
  GENERAL_STUDENT_CHALLENGE_LOG_FILE = 'GENERAL_STUDENT_CHALLENGE_LOG_FILE',
}
